version: '3'


services:
  nodeserver:
    build: .
    volumes:
      - .:/usr/app/
    ports:
      - "3000:3000"
    depends_on:
      - mongo_db
    environment:
      NODE_ENV: development

  mongo_db:
    image: mongo:3.6.9-stretch
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
